### ISSUE TITLE
Issues with monitors

### ISSUE THREAD

**Issue by HashSquatch** [dglt1/optimus-switch-sddm#3]
Follow on from closed ticket... 

# Intel active:
**inxi -Fxxxz:**
https://hastebin.com/qubukubeze.makefile
**mhwd -li:**
https://hastebin.com/ozijuvuvor.css
**ls -laR /etc/X11:**
https://hastebin.com/etazesuhej.diff
**cat /etc/X11/xorg.conf.d (I'm assuming ls):**
https://hastebin.com/udocacecex.md
**xrandr --prop:**
https://hastebin.com/elufewezoq.css
# Nvidia Active:
**inxi -Fxxxz:**
https://hastebin.com/eqabuyolox.makefile
**ls -laR /etxc/X11:**
https://hastebin.com/ijobepicip.diff
**cat /etc/X11/xorg.conf.d (I'm assuming the org file):**
https://hastebin.com/etavinojoh.makefile
**xrandr --prop:**
https://hastebin.com/tocecebene.css

**Comment by dglt1** [comment]
im not able to see anything on any of those hastebin links, its just a green background. i tried with vivaldi, firefox and even edge preview. maybe a different pastebin service. the manjaro has the pastebinit utility you could use to make things easier for yourself. 
usage:
`inxi -Fxxxz | pastebinit` which then provides a link to the pastebin.

original ticket:

> Hey,

Nice work on the scripts. I'm battling with a mysterious issue, where I run on dGPU mode, only my nvidia gpu is registered with xrandr. I believe the intel GPU is either powered off or not being registered at all. This is an issue as running with dGPU my eDP (Laptop screen) is not powered on however the HDMI port (External monitor) runs fine. And on intel mode, my laptop screen works and HDMI doesn't. Do you perhaps have any suggestion on what is going on?


i just went over the previously closed ticket and i was wondering if you happen to be using a display setup script of some kind either left over from before optimus switch? i ask this because the name used for the laptop display is different when on nvidia than it is with intel.
laptop display when using intel is eDP1 and on nvidia it's eDP-1-1 . 

i think to troubleshoot this would be much easier/faster for both of us if you sent me a message on the the manjaro forum, my username is `@dglt ` , this way we can troubleshoot in real time and post the solution to the issue here after it's figured out since im available on the forum much more than i am here. include the requested pastebin links. 

if the outputs check out, you may just need to add monitor/screen sections to the xorg configuration for each mode which is no big deal. 

please also explain what optimus setup were you using before optimus-switch (bumblebee?prime?nouveau?optimus-manager?) if you have tried more than 1 of those, just explain.

**Comment by HashSquatch** [comment]
Fixed by reinstalling manjaro completely. It seems to be the fault of some prime switchers before using optimus switcher.
