### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by Leinatan** [dglt1/optimus-switch-sddm#9]
Not really an issue, but I noticed a typo in the readme:

line 11: `lscpi -v | grep -E 'VGA|3D'` should be 'ls**pci** -v ...'

Otherwise I think the program runs nicely. Haven't really tested yet, but thank you anyway for the time spent on this ;)

If I may, does the prime mode autoswitch between the GPUs depending on the programs launched? I couldn't figure out...

**Comment by dglt1** [comment]
thanks, i'll fix the typo.

> does the prime mode autoswitch between the GPUs depending on the programs launched?

no, linux doesnt have a solution for auto switching like windows does. in prime mode the nvidia gpu does all the work and uses the intel to display it since only the intel is wired to the laptop display. no launch parameters are needed to use the nvidia gpu when using prime mode.
